### ISSUE TITLE
[BUG] Volume icon not showing in Google Definition box

### ISSUE THREAD

**Issue by hbarsaiyan** [benbusby/whoogle-search#259]
**Describe the bug**
Volume icon is not showing up in the Google Definition box.

**To Reproduce**
1. Search definition of any word.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [x] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version [3.2 develop branch]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Ungoogled Chromium
 - Version 89.0.4389.90

**Smartphone (please complete the following information):**
 - Device: Lenovo Tab4 X304-L
 - OS: Lineage OS 16
 - Browser: Bromite
 - Version 89.0.4389.117

**Additional context**
![Screenshot from 2021-04-03 16-06-38](https://user-images.githubusercontent.com/37732050/113476251-e7829780-9497-11eb-926a-9c83d1d43b31.png)

**Comment by benbusby** [comment]
Sorry for the delay -- this should be fixed now as of a7bf9728e30f53a5cfc3b295b5354dcfbf6440c0.

**Comment by hbarsaiyan** [comment]
@benbusby appologies for the late reply but this issue still persists. The SVGs are not being loaded.

![Screenshot_12](https://user-images.githubusercontent.com/37732050/120791067-59876380-c551-11eb-98c9-c7a17af7979d.png)

**Comment by benbusby** [comment]
Thanks for pointing this out, I'll look into it
