### ISSUE TITLE
[BUG] [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by FallenLeave91** [benbusby/whoogle-search#368]
**Describe the bug**
With the latest version my container won´t start anymore. I get this error:

```
today at 19:55:30 Jul 01 17:55:30.000 [notice] Bootstrapped 80%: Connecting to the Tor network
today at 19:55:30 Jul 01 17:55:30.000 [notice] Bootstrapped 85%: Finishing handshake with first hop
today at 19:55:30 Jul 01 17:55:30.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
today at 19:55:31 Jul 01 17:55:31.000 [notice] Bootstrapped 100%: Done
today at 19:55:33 Traceback (most recent call last):
today at 19:55:33   File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
today at 19:55:33     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
today at 19:55:33   File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
today at 19:55:33     return _get_module_details(pkg_main_name, error)
today at 19:55:33   File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
today at 19:55:33     __import__(pkg_name)
today at 19:55:33   File "/whoogle/app/__init__.py", line 94, in <module>
today at 19:55:33     os.makedirs(app.config['BUILD_FOLDER'])
today at 19:55:33   File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
today at 19:55:33     mkdir(name, mode)
today at 19:55:33 OSError: [Errno 30] Read-only file system: '/whoogle/app/static/build'
```

With benbusby/whoogle-search:0.5.4 everything works perfectly fine.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Comment by r0arkin** [comment]
I'm seeing the same exact issue after the last commit with Docker.

**Comment by SxthGear** [comment]
Same issue here.

**Comment by clecle226** [comment]
while waiting for the bug to be resolved:
in docker-compose, replace:
```
image: benbusby/whoogle-search
```
to
```
image: benbusby/whoogle-search:0.5.4
```

**Comment by benbusby** [comment]
Should be fixed now on the latest/beta Docker tags.

**Comment by r0arkin** [comment]
This is still not fixed for me. I even deleted the image and re-downloaded.

**Comment by FallenLeave91** [comment]
@r0arkin you have to edit the docker-compose.yml and remove the read only part.

**Comment by benbusby** [comment]
@r0arkin have you pulled latest changes from the repo? The images themselves are only part of the solution -- docker-compose.yml also needs to be updated. If you did pull and are using the latest changes, let me know and I can help debug further.

**Comment by r0arkin** [comment]
> @r0arkin have you pulled latest changes from the repo? The images themselves are only part of the solution -- docker-compose.yml also needs to be updated. If you did pull and are using the latest changes, let me know and I can help debug further. 

I ended up removing the read only flag as @FallenLeave91 suggested and that worked. I forgot to reply. Thanks for the help!
