### ISSUE TITLE
Social media alternative redirects no longer working

### ISSUE THREAD

**Issue by Deviantgit** [benbusby/whoogle-search#901]
My self-hosted docker deployment of Whoogle has been working flawlessly with me for the past year or so, apart from the occasional rate limit. However, since the latest Docker image was updated, social media redirects no longer work as intended all of a sudden. I am using other self-hosted services (Nitter, Libreddit, and Invidious) which I access through local domain names (e.g., nitter.local.domain).

**To Reproduce**
1. Go to Whoogle
2. Search any query that produces a Youtube or Reddit link (oddly enough, Twitter properly redirects to my Nitter instance)
3. Click on any Youtube or Reddit link, and it directs to Youtube or Reddit.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox 107, Safari 16

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.0.2
 - Browser Safari, Firefox 107.2

**Additional context**
I've noticed that in the search results page, Nitter, which works as intended, shows the preview URL as "nitter.local.domain". YouTube and Reddit have www prepended (e.g. www.invidious.local.domain, www.libreddit.local.domain). I have not changed hostnames in my router, nor have I changed the environment file from Whoogle (which was working, and has them listed as nitter.local.domain). Screenshot is attached.

Edit: I’ve noticed this also appears to be occurring with Wikipedia, Instagram, and Medium (which I’ve set in my environment variables to redirect to farside.link, so it would seem that it’s unrelated to some of my services being self-hosted)
![Screen Shot 2022-12-06 at 15 20 17](https://user-images.githubusercontent.com/18128353/206026670-6caeb0c4-814a-4fbf-9040-17a815c41836.png)

**Comment by benbusby** [comment]
Thanks for reporting -- this should be fixed now.

**Comment by Deviantgit** [comment]
Appreciate the quick fix, and thanks for all you do with this fantastic project!

**Comment by Deviantgit** [comment]
Unfortunately, I’ve realized that the issue is still persisting—thought it was fixed but it turns out I was using another Whoogle instance because I got rate limited. 

The same sites are still not redirecting to my internal domains (invidious.local.domain, libreddit.local.domain, etc.), or farside.link. Are there any details I can provide that’d be of assistance?

**Comment by benbusby** [comment]
@Deviantgit can you provide a sample search query that you're seeing the issue persist with? When I perform your search from your original post, I'm seeing the correct redirects for each result:

![ss](https://user-images.githubusercontent.com/33362396/206588045-c9228f38-5376-442a-aacd-fb178cb866e6.png)

**Comment by Deviantgit** [comment]
Solved it by updating my docker image a second time! I’m guessing that the initial docker update I did this morning was likely to a recent but not quite latest version—it’s working as intended now. Sorry for the false alarm

**Comment by Kirk1984** [comment]
Hello,

So I'm really lazy, so i don't have have domains but local IP Adresses linked as alternatives to my local docker setup. So invidious for example is "192.168.168.200:8011". that worked before, and after not doing Updates for some time i too get the www (www.192.168.168.200:8011).

So now none of my local alternatives work with whoogle.
